global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: notification-api
    static_configs:
      - targets: ['api:8080']

  - job_name: notification-workers
    static_configs:
      - targets:
          - 'worker-push-ios:9090'
          - 'worker-push-android:9090'
          - 'worker-sms:9090'
          - 'worker-email:9090'
        labels:
          component: worker
